[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "microsoft.sharepoint.termstore"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Area/Storage & File Management", "Vendor/Microsoft", "Name/Microsoft SharePoint Termstore", "SharePoint", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.sharepoint.termstore"

[build-options]
observabilityIncluded = true
